apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passit-services-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/CLD4-T2-IAMConan/Passit.git
    targetRevision: main
    path: terraform/argocd/applications
    directory:
      recurse: false
      # prod 환경: dev, dr, README 제외
      exclude: "*-dev.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
