apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    # ⭐ 직접 service-cs repository 참조 (submodule 대신)
    repoURL: https://github.com/CLD4-T2-IAMConan/service-cs.git
    targetRevision: main  # service-cs repo의 기본 브랜치
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
      values: |
        imagePullSecrets:
          - name: ghcr-secret
  
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
