apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    # ⭐ 직접 service-cs repository 참조 (submodule 대신)
    repoURL: https://github.com/CLD4-T2-IAMConan/service-cs.git
    targetRevision: main  # service-cs repo의 기본 브랜치
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
      values: |
        image:
          repository: ghcr.io/cld4-t2-iamconan/service-cs
          tag: latest
        imagePullSecrets:
          - name: ghcr-pull-secret
        ingress:
          enabled: true
          className: alb
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
            alb.ingress.kubernetes.io/backend-protocol: HTTP
          hosts:
            - host: cs-service.passit.com
              paths:
                - path: /
                  pathType: Prefix
          tls: []
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cs
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
