apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # ⭐ 직접 service-trade repository 참조 (submodule 대신)
    repoURL: https://github.com/CLD4-T2-IAMConan/service-trade.git
    targetRevision: main  # service-trade repo의 기본 브랜치
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: trade

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
